/// Flutter icons CustomIcons
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CustomIcons
///      fonts:
///       - asset: fonts/CustomIcons.ttf
///
///
/// * Font Awesome 4, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
/// * Meteocons, Copyright (C) 2012 by Alessio Atzeni
///         Author:    Alessio Atzeni
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://www.alessioatzeni.com
///
import 'package:flutter/widgets.dart';

class CustomIcon {
  CustomIcon._();

  static const _kFontFam = 'CustomIcon';

  static const IconData heart = IconData(0xe800, fontFamily: _kFontFam);
  static const IconData heartEmpty = IconData(0xe801, fontFamily: _kFontFam);
  static const IconData windyRainEmpty =
      IconData(0xe804, fontFamily: _kFontFam);
  static const IconData snowHeavyEmpty =
      IconData(0xe805, fontFamily: _kFontFam);
  static const IconData hailEmpty = IconData(0xe806, fontFamily: _kFontFam);
  static const IconData rain = IconData(0xe807, fontFamily: _kFontFam);
  static const IconData drizzle = IconData(0xe808, fontFamily: _kFontFam);
  static const IconData cloud = IconData(0xe809, fontFamily: _kFontFam);
  static const IconData rainEmpty = IconData(0xe80a, fontFamily: _kFontFam);
  static const IconData cloudSun = IconData(0xe80b, fontFamily: _kFontFam);
  static const IconData cloudMoon = IconData(0xe80c, fontFamily: _kFontFam);
  static const IconData cloudSunEmpty = IconData(0xe80d, fontFamily: _kFontFam);
  static const IconData cloudMoonEmpty =
      IconData(0xe80e, fontFamily: _kFontFam);
  static const IconData bookmark = IconData(0xe80f, fontFamily: _kFontFam);
  static const IconData comment = IconData(0xe810, fontFamily: _kFontFam);
  static const IconData chat = IconData(0xe811, fontFamily: _kFontFam);
  static const IconData tags = IconData(0xe812, fontFamily: _kFontFam);
  static const IconData tag = IconData(0xe813, fontFamily: _kFontFam);
  static const IconData bookmarkEmpty = IconData(0xf097, fontFamily: _kFontFam);
  static const IconData commentEmpty = IconData(0xf0e5, fontFamily: _kFontFam);
  static const IconData chatEmpty = IconData(0xf0e6, fontFamily: _kFontFam);
  static const IconData plusSquared = IconData(0xf0fe, fontFamily: _kFontFam);
  static const IconData plusSquaredEmpty =
      IconData(0xf196, fontFamily: _kFontFam);
  static const IconData share = IconData(0xf1e0, fontFamily: _kFontFam);
}
